### ISSUE TITLE
Can you add support for TextEditingController?

### ISSUE THREAD

**Issue by allanwolski** [edsonbonfim/form#2]
Sometimes it is necessary to update the values and use formatters.
By the way, can you add support for the other properties of TextField as well?

**Comment by edsonbonfim** [comment]
TextEditingController is coming in the next update. What other text field properties do you need?

**Comment by allanwolski** [comment]
Thanks, @edsonbonfim 

I need the initialValue property.
Do you have a date to release the next update?

**Comment by allanwolski** [comment]
> TextEditingController is coming in the next update. What other text field properties do you need?

Do you have a date to the next release?

**Comment by guilhermedaldim** [comment]
I also need this resource
